spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kicknclick
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    generate-ddl: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
  error:
    include-message: always